const express = require("express");
const connectDB = require("./config/db");
const dotenv = require("dotenv");
const cors = require("cors");
const swaggerUi = require("swagger-ui-express");
const swaggerSpecs = require("./swagger/swaggerOptions");
const { default: mongoose } = require("mongoose");
dotenv.config();
const app = express();
connectDB();
require("./cron/taskReminder");
app.use("/uploads", express.static("uploads"));
app.use(cors());
app.use(express.json());
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpecs));
app.use("/api", require("./routes/taskRoutes"));
app.use("/api/auth", require("./routes/authRoutes"));
const PORT = process.env.PORT || 5000;
mongoose.connect(process.env.MONGO_URI);

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
